name: Android CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Upload to Firebase Distribution
      run: |
        echo $FIREBASE_TOKEN | firebase login:ci
        firebase appdistribution:distribute ./app/build/outputs/apk/debug/app-debug.apk --app <YOUR_FIREBASE_APP_ID> --groups <YOUR_DISTRIBUTION_GROUPS> --release-notes "New build available" --token $FIREBASE_TOKEN
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
